// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhjPo1ncDZf8qDw9X96dzR_M69C5Buvug',
    appId: '1:724565748018:web:d4c2198b7f71884bcc8f2b',
    messagingSenderId: '724565748018',
    projectId: 'german-kaksha',
    authDomain: 'german-kaksha.firebaseapp.com',
    storageBucket: 'german-kaksha.firebasestorage.app',
    measurementId: 'G-H219NBCR3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjVQlViU7rzv87S9Qvqywii3hwI4JBDn0',
    appId: '1:724565748018:android:d63be2519bad9020cc8f2b',
    messagingSenderId: '724565748018',
    projectId: 'german-kaksha',
    storageBucket: 'german-kaksha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdiWrorG7EEAH6g7UdC3_VlaD5r5gpJOA',
    appId: '1:724565748018:ios:608241d707176347cc8f2b',
    messagingSenderId: '724565748018',
    projectId: 'german-kaksha',
    storageBucket: 'german-kaksha.firebasestorage.app',
    iosBundleId: 'com.example.germanKaksha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdiWrorG7EEAH6g7UdC3_VlaD5r5gpJOA',
    appId: '1:724565748018:ios:608241d707176347cc8f2b',
    messagingSenderId: '724565748018',
    projectId: 'german-kaksha',
    storageBucket: 'german-kaksha.firebasestorage.app',
    iosBundleId: 'com.example.germanKaksha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhjPo1ncDZf8qDw9X96dzR_M69C5Buvug',
    appId: '1:724565748018:web:755e32565c5655f9cc8f2b',
    messagingSenderId: '724565748018',
    projectId: 'german-kaksha',
    authDomain: 'german-kaksha.firebaseapp.com',
    storageBucket: 'german-kaksha.firebasestorage.app',
    measurementId: 'G-8QBJ3NXFZY',
  );
}
